---
- include:              '../tasks/lines_in_files.yml'
- include:              '../tasks/lines_in_files.yml'
  vars:
    lines_in_files:     "{{ lines_in_files_unique_port }}"
  when:                 unique_port is defined
- include:              '../tasks/install_files.yml'
- include:              '../tasks/restart_services.yml'
  when:                 install_files_result.changed
                        or lines_in_files_result.changed
