---
- include_tasks:        '../tasks/remove_packages.yml'
- include_tasks:        '../tasks/install_packages.yml'
- command:              chattr -i /etc/ssh/ssh_host_rsa_key
  changed_when:         False
- command:              chattr -i /etc/ssh/ssh_host_rsa_key.pub
  changed_when:         False
- include_tasks:        '../tasks/lines_in_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- command:              chattr +i /etc/ssh/ssh_host_rsa_key
  changed_when:         False
- command:              chattr +i /etc/ssh/ssh_host_rsa_key.pub
  changed_when:         False
- include_tasks:        '../tasks/restart_services.yml'
  when:                 install_files_result.changed
                        or lines_in_files_result.changed
