---
- include:              '../tasks/remove_packages.yml'
- include:              '../tasks/lines_in_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/restart_services.yml'
  when:                 install_files_result.changed
                        or lines_in_files_result.changed
